const express = require('express')
const {createProduct,getProducts,getProductsById,updateProducts,deleteProduct} = require('../controllers/productController')
const router = express.Router()
const   middleWarefunc= require('../middleware/authmiddleware')
const adminmiddleware = require('../middleware/adminmiddleware')
router.post('/', middleWarefunc,adminmiddleware,createProduct)
router.get('/',getProducts)
router.get('/:id',getProductsById)
router.put('/:id', middleWarefunc,adminmiddleware,updateProducts)
router.delete('/:id', middleWarefunc,adminmiddleware, deleteProduct)
module.exports = router;